가속도 센서를 이용한 충돌 감지 기능 추가
SO-SI-JI/Accident-Here-IOS pull request #6
Opened 2022-01-03 13:52 UTC by yjs1213

- GPS에서 가져온 값이 `baseline` 이상이면, 충돌 감지 시작
- 가속도 변화량이 충돌 민감도보다 크면 `충돌 감지중` label 폰트 색상 변경, Blop Sound 재생

2022-01-05 01:34 UTC, elis0m requested changes
제가 요즘 lint 같은 정적 도구들을 공부하는 중이라....... 👾
고생하셨습니다요

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
> +                    if val_x > sensitivityValue || val_y > sensitivityValue || val_z > sensitivityValue{
```suggestion
                    if val_x > sensitivityValue || val_y > sensitivityValue || val_z > sensitivityValue {
```
[SwiftLint](https://github.com/realm/SwiftLint) 사용하면 좋았을 것 같아요👀
한 번 확인해보셔염 👍 [Swift Style Guide](https://google.github.io/swift/)

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
> +    }
```suggestion
    func initPlay() {
        do {
            audioPlayer = try AVAudioPlayer(contentsOf: audioFile)
        } catch let error as NSError {
            print("Error Initial Play")
        }
        audioPlayer.prepareToPlay()
    }
```

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
> +            let timer = Timer(fire: Date(), interval: (1.0/60.0), repeats: true, block: { (timer) in
```suggestion
            let timer = Timer(fire: Date(), interval: (1.0 / 60.0), repeats: true, block: { (timer) in
```

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
>              }
제가 작성했던 코드지만, 리뷰하면서 보니 **기준속도 이상**과 **이하**일 때 뷰 처리를 함수로 각각 만들면 좋을 것 같아요
근데 갑자기 드는 생각이 위급상황도 아니고, 속도 좀 빠르다고 화면이 빨간색 되는 건 좀 과한 거 아닌가여? 😓ㅋㅋㅋㅋ

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
> +                        self.audioPlayer.play()
충돌 감지도 기준속도 이상, 이하일 때처럼 함수로 빼면 좋겠군요 🤔

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
> +    var audioFile : URL!
```suggestion
    var audioFile: URL!
```

2022-01-05 01:34 UTC, elis0m commented on AccidentHere/ViewController.swift
> +    var audioPlayer : AVAudioPlayer!
```suggestion
    var audioPlayer: AVAudioPlayer!
```

2022-01-18 10:35 UTC, yjs1213 commented on AccidentHere/ViewController.swift
> +                    if val_x > sensitivityValue || val_y > sensitivityValue || val_z > sensitivityValue{
꿀팁 감사합니다 😊

2022-01-18 10:35 UTC, yjs1213 commented on AccidentHere/ViewController.swift
> +    }
반영했습니다~

2022-01-18 10:35 UTC, yjs1213 commented on AccidentHere/ViewController.swift
> +            let timer = Timer(fire: Date(), interval: (1.0/60.0), repeats: true, block: { (timer) in
반영했습니다~

2022-01-18 10:36 UTC, yjs1213 commented on AccidentHere/ViewController.swift
>              }
넵 그렇게 진행하시죠!

2022-01-18 10:36 UTC, yjs1213 commented on AccidentHere/ViewController.swift
> +                        self.audioPlayer.play()
넵 알겠습니다~

2022-01-18 10:36 UTC, yjs1213 commented on AccidentHere/ViewController.swift
> +    var audioFile : URL!
반영했습니다~

2022-01-18 10:36 UTC, yjs1213 commented on AccidentHere/ViewController.swift
> +    var audioPlayer : AVAudioPlayer!
반영했습니다~

2022-01-18 12:17 UTC, elis0m commented on AccidentHere/ViewController.swift
>              }
넵 추후에 반영합시다!

2022-01-18 12:17 UTC, elis0m commented on AccidentHere/ViewController.swift
> +                        self.audioPlayer.play()
네 다음번에 확인해봅시다!~

2022-01-18 12:30 UTC, elis0m approved these changes

2022-01-18 12:30 UTC, merged